travis:
  secure:
    BINSTAR_TOKEN: apqhG6JYMbx87CDLFF3aMXJGV3YfEDt0ZS1t4V1nNvutsG4gLUzhjoAYCgIEiOmdKlyxyHu0f8YzAyUgK+b6fjyXH9Rakl1w6Ty6p59zvAUF+UTDLKQmLdMoGh+6Hr6rnjWMPyoyeG8gIolFY8wDOVs5H4SniO9EP000MAWE7uExPTZxy4Yca3Tc8VXeEY+/APnj5/vaeChhbwRd45gntrz7O7LjLVuhT0gsN9t9UcVnDPlcIrtVuTmO4UeG7d5+pDrljePwRiosB0l1bbfOJ6e5bIOf4gdBJax7KMnhj33Y4l0ha34TjNWIaUY6hi+VxmkD8+0hPKJMb6jLbNQEcuIcgcN7No7UIaKMTy+YQ7dDP+oQh05J94fil3dLVYG7fEg0c2RAeYMnV5AjXLY+6WlzzQrN8tiUr1Jl14QBFOYahBg1KK+e9QR+z960fXZizHkjZlW3f6W/NiPqm1ae1ujYGCytTj+4yl8jrkLB4Rr/LEsafC3IQX4h8h3x+aawqHqZjvrCOtXAYvyW2QV/xhA8OPpXvEibCielGNYxoAxDfPZsThlACUuTzO1mMnzK32v7bNSEyzyvmDjOuF2S1cbW518TxvG4XClVT65/eTkM+DhCEIN9MdHHEDunc/ry7DYv8PPywGFCrcbQ76HJeSr6eyYlnw62juWUPMs7ks8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
